"""description field

Revision ID: 3cb2bb0319cb
Revises: 46b004895f44
Create Date: 2023-09-06 16:26:20.698653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb2bb0319cb'
down_revision = '46b004895f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gptResponse', sa.String(length=5000), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('gptResponse')

    # ### end Alembic commands ###
