"""Added none option to question 5

Revision ID: 43370cb73381
Revises: 5ab3d59fd1dd
Create Date: 2023-07-27 00:04:09.995676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43370cb73381'
down_revision = '5ab3d59fd1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q_5_none', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_response', schema=None) as batch_op:
        batch_op.drop_column('q_5_none')

    # ### end Alembic commands ###
