"""Questionarie check

Revision ID: 5ab3d59fd1dd
Revises: e6f569d498a0
Create Date: 2023-07-26 23:42:30.554261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab3d59fd1dd'
down_revision = 'e6f569d498a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questionaire_filled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('questionaire_filled')

    # ### end Alembic commands ###
