"""description field

Revision ID: 5c452f32edea
Revises: 3cb2bb0319cb
Create Date: 2023-09-06 16:30:03.958256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c452f32edea'
down_revision = '3cb2bb0319cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('gptResponse',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('gptResponse',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)

    # ### end Alembic commands ###
