"""Questions date field in the UserResponse table

Revision ID: 988fb2ad8bd5
Revises: 5c452f32edea
Create Date: 2023-09-06 23:03:54.753574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988fb2ad8bd5'
down_revision = '5c452f32edea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_response', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
