"""Changing column type.

Revision ID: e6f569d498a0
Revises: 90a0ab4fe830
Create Date: 2023-07-26 07:27:11.268091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f569d498a0'
down_revision = '90a0ab4fe830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('q_1', sa.String(length=10), nullable=True),
    sa.Column('q_2', sa.String(length=10), nullable=True),
    sa.Column('q_3', sa.String(length=10), nullable=True),
    sa.Column('q_4', sa.String(length=100), nullable=True),
    sa.Column('q_5_breathing', sa.String(length=100), nullable=True),
    sa.Column('q_5_chest', sa.String(length=100), nullable=True),
    sa.Column('q_5_speech', sa.String(length=100), nullable=True),
    sa.Column('q_5_pale', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_response')
    # ### end Alembic commands ###
